### ISSUE TITLE
vrchat apk and more applications?

### ISSUE THREAD

**Issue by nglmercer** [thoricelli/OculusXRPicoLayer#2]
There is a version of vrchat in pico 4 and the apk exists. I have a pico neo 3 and it has a bug. There is a discord channel and server called owomushi. You will find there and there is also a telegram from another one that also shares quest and pico apks.
![image](https://github.com/thoricelli/OculusXRPicoLayer/assets/128845117/874e2473-6026-49e0-8caf-ee2c23d8df7a)
If this works well or maybe I should extract the apk on a quest device

**Comment by thoricelli** [comment]
Hi
Thanks for the tips, I will check it out.

I mainly needed the VRChat APK because I wanted to try and implement the hand/eye tracking.
But, I'll have to mainly focus on getting games to work _at all_ before I try implementing features.
